# Generated by Django 3.1.7 on 2021-03-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210330_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='ISO',
        ),
        migrations.RemoveField(
            model_name='language',
            name='ISO',
        ),
    ]
