# Generated by Django 3.1.7 on 2021-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210330_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Specification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
