# Generated by Django 3.1.7 on 2021-04-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tagline', models.CharField(max_length=255)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.group')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.language')),
            ],
            options={
                'verbose_name_plural': 'Groups Info',
            },
        ),
        migrations.AddConstraint(
            model_name='groupinfo',
            constraint=models.UniqueConstraint(fields=('Group', 'Language'), name='unique_GroupInfo'),
        ),
    ]
