# Generated by Django 3.1.7 on 2021-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210401_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='Flag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
