# Generated by Django 3.1.7 on 2021-04-02 11:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210402_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='Text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
