# Generated by Django 3.1.7 on 2021-04-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0010_auto_20210406_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(choices=[(1, 'Customer Order'), (2, 'Supply Order'), (3, 'Received Payment'), (4, 'Sent Payment'), (5, 'Delivered Goods'), (6, 'Received Goods'), (7, 'Deposited Money'), (8, 'Withdrawn money')], null=True)),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
                ('Counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.counterparty')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
