# Generated by Django 3.1.7 on 2021-04-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_auto_20210407_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='Order',
        ),
    ]
