# Generated by Django 3.1.7 on 2021-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20210407_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationposition',
            name='CustomerOrderStatus',
            field=models.IntegerField(choices=[(1, 'In stock / prepared for delivery'), (2, 'In stock / should be ordered'), (3, 'Not in stock / need to be ordered'), (4, 'Not in stock / waiting for incoming'), (5, 'Not in stock / no delivery control'), (6, 'Delivered to customer')], null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Customer Order'), (2, 'Supply Order'), (3, 'Received Payment'), (4, 'Sent Payment'), (5, 'Delivered Goods'), (6, 'Received Goods'), (7, 'Deposited Money'), (8, 'Withdrawn money'), (9, 'Break set to items')], null=True),
        ),
    ]
