# Generated by Django 3.1.7 on 2021-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_auto_20210408_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationposition',
            name='CustomerOrderStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'In stock / prepared for delivery'), (2, 'In stock / should be ordered'), (3, 'Not in stock / need to be ordered'), (4, 'Not in stock / waiting for incoming'), (5, 'Not in stock / no delivery control'), (6, 'Delivered to customer')], null=True),
        ),
    ]
