# Generated by Django 3.1.7 on 2021-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_auto_20210411_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationatom',
            options={'verbose_name_plural': 'Operation Atoms'},
        ),
        migrations.AlterModelOptions(
            name='operationposition',
            options={'verbose_name_plural': 'Operation Positions'},
        ),
        migrations.AddField(
            model_name='operationposition',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operationposition',
            name='DiscountReason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='operation',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Customer Order'), (2, 'Supplier Order'), (3, 'Received Payment'), (4, 'Sent Payment'), (5, 'Delivered Goods'), (6, 'Received Goods'), (7, 'Deposited Money'), (8, 'Withdrawn money'), (9, 'Break set to items')], null=True),
        ),
    ]
