# Generated by Django 3.2 on 2021-04-11 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_setproducts'),
        ('ledger', '0023_auto_20210411_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationatom',
            name='Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account'),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency'),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='DateAtom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationatom',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='Quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='State',
            field=models.IntegerField(blank=True, choices=[(1, 'Actual'), (2, 'Reserved'), (3, 'Ordered')], null=True),
        ),
        migrations.AddField(
            model_name='operationatom',
            name='Type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
