# Generated by Django 3.2 on 2021-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_itemsetbreakdown_itemsetbreakdownposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='GreenwayOrderId',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
