# Generated by Django 3.2 on 2021-04-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_price_comment'),
        ('ledger', '0043_auto_20210427_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='Memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierorderposition',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency'),
        ),
        migrations.AlterField(
            model_name='supplierorderposition',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
