# Generated by Django 3.2 on 2021-04-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_price_comment'),
        ('ledger', '0045_alter_supplierorder_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='DatePlaced',
        ),
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(help_text='Account name that is easy to use and remember.', max_length=50, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid by Customer.', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Currency',
            field=models.ForeignKey(blank=True, help_text='Currency of Customer payment.', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDelivered',
            field=models.DateField(blank=True, help_text='Date when this Order was delivered to the Customer. In case of Detailed Delivery, the date of last delivery is used.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDispatched',
            field=models.DateField(blank=True, help_text='Date when this Order was dispatched to the Customer.Until then, the Order is prepared but held in Storage.', null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DetailedDelivery',
            field=models.BooleanField(default=False, help_text='Delivery of each Position is managed separately', verbose_name='Detailed Delivery'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Memo',
            field=models.TextField(blank=True, help_text='Meme related to this Customer Order', verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='TrackingNumber',
            field=models.CharField(blank=True, help_text='Tracking Number provided by used Courier Service.', max_length=50, verbose_name='Tracking Number'),
        ),
    ]
