# Generated by Django 3.2 on 2021-04-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_price_comment'),
        ('ledger', '0046_auto_20210428_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Name',
            field=models.CharField(help_text='Name of the Counterparty, preferably "Surname Name"', max_length=50, verbose_name='Counterparty Name'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Memo',
            field=models.TextField(blank=True, help_text='Memo related to this Customer Order', verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='DateOperation',
            field=models.DateField(help_text='Date when this Operation was executed', verbose_name='Operation Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ParentOperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Parent', to='ledger.operation'),
        ),
    ]
