# Generated by Django 3.2 on 2021-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_auto_20210429_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('CZP', 'Czech Post'), ('POST', 'Ordinary Post')], max_length=10, null=True),
        ),
    ]
