# Generated by Django 3.2 on 2022-01-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_action_originalurl'),
        ('ledger', '0055_auto_20210504_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('AKIS', 'Akis Express'), ('CZP', 'Czech Post'), ('POST', 'Ordinary Post'), ('GLS', 'GLS Post Service')], help_text='Select one from provided Courier Services', max_length=10, null=True, verbose_name='Courier Service Name'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to the Supplier.', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Counterparty',
            field=models.ForeignKey(blank=True, help_text='Registered Supplier', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.counterparty', verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('AKIS', 'Akis Express'), ('CZP', 'Czech Post'), ('POST', 'Ordinary Post'), ('GLS', 'GLS Post Service')], help_text='Select one from provided Courier Services', max_length=10, null=True, verbose_name='Courier Service Name'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Currency',
            field=models.ForeignKey(blank=True, help_text='Currency of Supplier payment.', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DateDelivered',
            field=models.DateField(blank=True, help_text='Date when this Order was delivered from the Supplier to Storage.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DateDispatched',
            field=models.DateField(blank=True, help_text='Date when this Order was dispatched from the Supplier.', null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DatePlaced',
            field=models.DateField(blank=True, help_text='Date when this Order was placed to the Supplier system.', null=True, verbose_name='Placement Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='GFT',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift value calculated in GFT (obsolete since 07.07.2021).', max_digits=10, null=True, verbose_name='GFT Value'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='GreenwayOrderNum',
            field=models.CharField(blank=True, help_text='Number of this Order in the Suppliers system.', max_length=10, verbose_name='Supplier Order Num'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Memo',
            field=models.TextField(blank=True, help_text='Memo related to this Supplier Order', verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='TrackingNumber',
            field=models.CharField(blank=True, help_text='Tracking Number provided by used Courier Service.', max_length=50, verbose_name='Tracking Number'),
        ),
    ]
