# Generated by Django 3.2.9 on 2021-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_auto_20210504_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsetbreakdown',
            name='Memo',
            field=models.TextField(blank=True, help_text='Memo related to this ItemSet Breakdown', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='operationposition',
            name='TransactionType',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='X', max_length=1),
            preserve_default=False,
        ),
    ]
