# Generated by Django 3.2 on 2022-01-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_action_originalurl'),
        ('ledger', '0056_auto_20220105_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='DeliveryPrice',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of delivery in the same currency as Amount, if separately                                         provided by the Supplier', max_digits=10, null=True, verbose_name='Delivery price'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='Gift',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift value calculated in payment Currency (actual since 07.07.2021)', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='supplierorderposition',
            name='GiftPosition',
            field=models.BooleanField(default=False, help_text='This Position is purchased from accrued Gift funds', verbose_name='Gift'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid by Customer', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='Currency',
            field=models.ForeignKey(blank=True, help_text='Currency of Customer payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDelivered',
            field=models.DateField(blank=True, help_text='Date when this Order was delivered to the Customer.                                                  In case of Detailed Delivery, the date of last delivery is used', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDispatched',
            field=models.DateField(blank=True, help_text='Date when this Order was dispatched to the Customer. Until then,                                                   the Order is prepared but held in Storage', null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='TrackingNumber',
            field=models.CharField(blank=True, help_text='Tracking Number provided by used Courier Service', max_length=50, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to the Supplier', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Currency',
            field=models.ForeignKey(blank=True, help_text='Currency of Supplier payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DateDelivered',
            field=models.DateField(blank=True, help_text='Date when this Order was delivered from the Supplier to Storage', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DateDispatched',
            field=models.DateField(blank=True, help_text='Date when this Order was dispatched from the Supplier', null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DatePlaced',
            field=models.DateField(blank=True, help_text='Date when this Order was placed to the Supplier system', null=True, verbose_name='Placement Date'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='GFT',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift value calculated in GFT (obsolete since 07.07.2021)', max_digits=10, null=True, verbose_name='GFT Value'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='GreenwayOrderNum',
            field=models.CharField(blank=True, help_text='Number of this Order in the Suppliers system', max_length=10, verbose_name='Supplier Order Num'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='PV',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume (PV) obtained from this Order', max_digits=10, null=True, verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='TrackingNumber',
            field=models.CharField(blank=True, help_text='Tracking Number provided by used Courier Service', max_length=50, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='supplierorderposition',
            name='FreeOnAction',
            field=models.BooleanField(default=False, help_text='This Position is free because of ongoing Action', verbose_name='Free Item'),
        ),
        migrations.AlterField(
            model_name='supplierorderposition',
            name='PV',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume (PV) obtained per one Product', max_digits=10, null=True, verbose_name='PV'),
        ),
    ]
