# Generated by Django 3.2 on 2022-01-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_auto_20220105_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='GFT',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift value calculated in GFT (obsolete since 07.07.2021)', max_digits=10, null=True, verbose_name='GFT Amount'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Gift',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift value calculated in payment Currency (actual since 07.07.2021)', max_digits=10, null=True, verbose_name='Gift Amount'),
        ),
    ]
