# Generated by Django 3.2 on 2022-01-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_auto_20211221_1903'),
        ('ledger', '0058_auto_20220105_2020'),
    ]

    operations = [
    ]
