# Generated by Django 3.2.9 on 2022-01-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_action_dateend'),
        ('ledger', '0059_merge_0057_auto_20211221_1903_0058_auto_20220105_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.operation')),
                ('DebitAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('CreditAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('Memo', models.TextField(blank=True, help_text='Memo related to this Cash Transfer', verbose_name='Memo')),
                ('CreditAccount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to='ledger.account')),
                ('CreditCurrency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_currency', to='products.currency')),
                ('DebitAccount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_account', to='ledger.account')),
                ('DebitCurrency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_currency', to='products.currency')),
            ],
            options={
                'verbose_name_plural': 'Cash Transfers',
            },
            bases=('ledger.operation', models.Model),
        ),
    ]
