# Generated by Django 3.2.9 on 2022-01-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0061_auto_20220111_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='DeliveryPrice',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of delivery in the same currency as Amount, if Customer                                         is charged for it. Included in total Amount.', max_digits=10, null=True, verbose_name='Delivery price'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='DeliveryPrice',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of delivery in the same currency as Amount, if separately                                         provided by the Supplier. Included in total Amount.', max_digits=10, null=True, verbose_name='Delivery price'),
        ),
    ]
