# Generated by Django 4.0.2 on 2022-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_alter_customerorder_datedelivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderposition',
            name='Currency',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='Coordinates',
            field=models.CharField(blank=True, help_text='Coordinates (in digital form, separated by comma) to be shown on the map', max_length=50, verbose_name='Map Coordinates'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Email',
            field=models.CharField(blank=True, help_text='Contact email', max_length=50, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Facebook',
            field=models.CharField(blank=True, help_text='Profile name used in Facebook and Facebook Messenger', max_length=50, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Instagram',
            field=models.CharField(blank=True, help_text='Instagram profile name', max_length=50, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Memo',
            field=models.TextField(blank=True, help_text='Comment', verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Name',
            field=models.CharField(help_text='Name of the Counterparty, preferably in format "Surname Name"', max_length=50, verbose_name='Counterparty Name'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Phone',
            field=models.CharField(blank=True, help_text='Contact phone, including area code', max_length=50, verbose_name='Contact Phone'),
        ),
    ]
