# Generated by Django 4.0.2 on 2022-03-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_action_dateend'),
        ('ledger', '0066_remove_customerorderposition_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='Currency',
            field=models.ForeignKey(blank=True, help_text='Currency of all amounts in this Customer Order', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='Currency'),
        ),
    ]
