# Generated by Django 4.1.1 on 2022-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_remove_customerorderposition_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('AKIS', 'Akis Express'), ('ACS', 'ACS Courier'), ('CZP', 'Czech Post'), ('POST', 'Ordinary Post'), ('GLS', 'GLS Post Service')], help_text='Select one from provided Courier Services', max_length=10, null=True, verbose_name='Courier Service Name'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('AKIS', 'Akis Express'), ('ACS', 'ACS Courier'), ('CZP', 'Czech Post'), ('POST', 'Ordinary Post'), ('GLS', 'GLS Post Service')], help_text='Select one from provided Courier Services', max_length=10, null=True, verbose_name='Courier Service Name'),
        ),
    ]
