# Generated by Django 3.2.2 on 2021-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featurette',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carouselinfo',
            name='Header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carouselinfo',
            name='Text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='featuretteinfo',
            name='Header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='featuretteinfo',
            name='Text',
            field=models.TextField(blank=True),
        ),
    ]
