# Generated by Django 3.2.2 on 2021-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20210513_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='Order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='Order',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='featurette',
            constraint=models.UniqueConstraint(fields=('Order',), name='unique_Featurette'),
        ),
    ]
