# Generated by Django 3.2.2 on 2021-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_carousel_headerclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='ButtonActionParameter',
            field=models.CharField(blank=True, help_text='Optional parameter to build action URL', max_length=255, verbose_name='Button Action Parameter'),
        ),
    ]
