# Generated by Django 3.1.7 on 2021-04-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenwayuser',
            name='ManagingPartner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.greenwayuser'),
            preserve_default=False,
        ),
    ]
