# Generated by Django 3.1.7 on 2021-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210330_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='Text',
            field=models.TextField(blank=True),
        ),
    ]
