# Generated by Django 3.1.7 on 2021-04-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210403_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Category',
        ),
    ]
