# Generated by Django 3.1.7 on 2021-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210404_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
