# Generated by Django 3.2 on 2021-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210414_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='Tagline',
            field=models.CharField(blank=True, help_text='A catchphrase or slogan that can make the product remembered.', max_length=255, verbose_name='Tagline'),
        ),
    ]
