# Generated by Django 3.2 on 2021-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_categoryinfo_longdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Product',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='products.Product'),
        ),
    ]
