# Generated by Django 3.2 on 2021-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210419_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='Comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
