# Generated by Django 3.1.7 on 2021-04-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20210406_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name_plural': 'Counterparties'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='DateCreated',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
