# Generated by Django 3.1.7 on 2021-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20210406_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DateDelivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='DateDispatched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='DatePlaced',
            field=models.DateField(blank=True, null=True),
        ),
    ]
