# Generated by Django 3.1.7 on 2021-04-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_tag_slug'),
        ('ledger', '0009_auto_20210406_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomCashOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtomProductOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderposition',
            name='Currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.currency'),
            preserve_default=False,
        ),
    ]
