# Generated by Django 3.2 on 2021-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_operation_dateoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='DateDelivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='DateDispatched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='DatePlaced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='TrackingNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
