# Generated by Django 3.2 on 2021-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_auto_20210407_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
                ('Operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.operation')),
            ],
        ),
    ]
