# Generated by Django 3.2 on 2021-04-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productinfo_tagline'),
        ('ledger', '0024_auto_20210411_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account'),
        ),
        migrations.AddField(
            model_name='operation',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency'),
        ),
        migrations.AddField(
            model_name='operation',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='operation',
            name='Quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='RelatedOperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='State',
            field=models.IntegerField(blank=True, choices=[(1, 'Actual'), (2, 'Reserved'), (3, 'Ordered')], null=True),
        ),
    ]
