# Generated by Django 3.2 on 2021-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20210415_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationposition',
            name='PV',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
