# Generated by Django 3.2 on 2021-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_operationposition_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='City',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='Instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(help_text='Account name that is easy to use and remember', max_length=50, verbose_name='Account Name'),
        ),
    ]
