# Generated by Django 3.2 on 2021-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_operation_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationposition',
            name='DateDelivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
