# Generated by Django 3.2 on 2021-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_operationposition_datedelivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='DetailedDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
