# Generated by Django 3.2 on 2021-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_operation_detaileddelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='CourierService',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('Post', 'Ordinary Post')], max_length=10, null=True),
        ),
    ]
