# Generated by Django 3.2 on 2021-04-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210419_1208'),
        ('ledger', '0032_operation_courierservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Counterparty',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='CourierService',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='DateDelivered',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='DateDispatched',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='DatePlaced',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='DetailedDelivery',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='PV',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='RelatedOperation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='State',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='TrackingNumber',
        ),
        migrations.CreateModel(
            name='OperSupplierOrder',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.operation')),
                ('DatePlaced', models.DateField(blank=True, null=True)),
                ('DateDispatched', models.DateField(blank=True, null=True)),
                ('DateDelivered', models.DateField(blank=True, null=True)),
                ('TrackingNumber', models.CharField(blank=True, max_length=50)),
                ('CourierService', models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('Post', 'Ordinary Post')], max_length=10, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PV', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.counterparty')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
            ],
            bases=('ledger.operation',),
        ),
    ]
