# Generated by Django 3.2 on 2021-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0034_rename_opersupplierorder_supplierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='GFT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
