# Generated by Django 3.2 on 2021-04-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210419_1208'),
        ('ledger', '0035_supplierorder_gft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.operation')),
                ('DatePlaced', models.DateField(blank=True, null=True)),
                ('DateDispatched', models.DateField(blank=True, null=True)),
                ('DateDelivered', models.DateField(blank=True, null=True)),
                ('TrackingNumber', models.CharField(blank=True, max_length=50)),
                ('CourierService', models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('Post', 'Ordinary Post')], max_length=10, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.counterparty')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
            ],
            options={
                'verbose_name_plural': 'Customer Orders',
            },
            bases=('ledger.operation',),
        ),
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'verbose_name_plural': 'Supplier Orders'},
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='CustomerOrderStatus',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='DateDelivered',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='DiscountReason',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='PV',
        ),
        migrations.RemoveField(
            model_name='operationposition',
            name='Price',
        ),
        migrations.CreateModel(
            name='SupplierOrderPosition',
            fields=[
                ('operationposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.operationposition')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DiscountReason', models.CharField(blank=True, max_length=50)),
                ('GFT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PV', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
            ],
            options={
                'verbose_name_plural': 'Supplier Order Positions',
            },
            bases=('ledger.operationposition',),
        ),
        migrations.DeleteModel(
            name='OperationAtom',
        ),
    ]
