# Generated by Django 3.2 on 2021-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0037_customerorderposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='DetailedDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
