# Generated by Django 3.2 on 2021-04-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_price_comment'),
        ('ledger', '0041_rename_greenwayorderid_supplierorder_greenwayordernum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.operation')),
                ('TransactionType', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
                ('ParentOperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Parent', to='ledger.operation')),
            ],
            bases=('ledger.operation',),
        ),
    ]
