# Generated by Django 3.2 on 2021-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorderposition',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='supplierorderposition',
            name='DiscountReason',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='Memo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='Memo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderposition',
            name='FreeOnAction',
            field=models.BooleanField(default=False),
        ),
    ]
