# Generated by Django 3.2 on 2021-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_auto_20210427_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='Memo',
            field=models.TextField(blank=True),
        ),
    ]
