# Generated by Django 3.2 on 2021-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0049_alter_supplierorder_courierservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='Address',
            field=models.CharField(blank=True, help_text='Address (without city)', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='City',
            field=models.CharField(blank=True, help_text='City name only', max_length=50, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Email',
            field=models.CharField(blank=True, help_text='Name of the Counterparty, preferably "Surname Name"', max_length=50, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Facebook',
            field=models.CharField(blank=True, help_text='Name used in Facebook and Facebook Messenger', max_length=50, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Instagram',
            field=models.CharField(blank=True, help_text='Name of the Counterparty, preferably "Surname Name"', max_length=50, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Memo',
            field=models.TextField(blank=True, help_text='Name of the Counterparty, preferably "Surname Name"', verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Phone',
            field=models.CharField(blank=True, help_text='Name of the Counterparty, preferably "Surname Name"', max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Telegram',
            field=models.CharField(blank=True, help_text='Telegram profile name', max_length=50, verbose_name='Telegram'),
        ),
    ]
