# Generated by Django 3.2 on 2021-05-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_auto_20210501_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderposition',
            old_name='CustomerOrderStatus',
            new_name='Status',
        ),
    ]
