# Generated by Django 3.2 on 2021-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_rename_customerorderstatus_customerorderposition_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='Counterparty',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDelivered',
            field=models.DateField(blank=True, help_text='Date when this Order was delivered to the Customer.                                                  In case of Detailed Delivery, the date of last delivery is used.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='DateDispatched',
            field=models.DateField(blank=True, help_text='Date when this Order was dispatched to the Customer. Until then,                                                   the Order is prepared but held in Storage.', null=True, verbose_name='Dispatch Date'),
        ),
        migrations.AlterField(
            model_name='customerorderposition',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount applied to total amount for the position.', max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='customerorderposition',
            name='Price',
            field=models.DecimalField(decimal_places=2, help_text='Paid price per one Product', max_digits=10, verbose_name='Price'),
        ),
    ]
