# Generated by Django 3.1.7 on 2021-03-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_price_pv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name_plural': 'Products Info'},
        ),
        migrations.AlterField(
            model_name='price',
            name='PV',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
