# Generated by Django 3.1.7 on 2021-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('Code',), name='unique_Currency'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('Code',), name='unique_Language'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('Product', 'Currency', 'DateAdded'), name='unique_Price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('SKU',), name='unique_Product'),
        ),
        migrations.AddConstraint(
            model_name='productinfo',
            constraint=models.UniqueConstraint(fields=('Product', 'Language'), name='unique_ProductInfo'),
        ),
        migrations.AddConstraint(
            model_name='tab',
            constraint=models.UniqueConstraint(fields=('Product', 'Language', 'Order'), name='unique_Tab'),
        ),
    ]
