# Generated by Django 3.1.7 on 2021-04-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.group'),
            preserve_default=False,
        ),
    ]
