# Generated by Django 3.1.7 on 2021-04-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210403_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupInfo',
            new_name='CategoryInfo',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_Group',
        ),
        migrations.RemoveConstraint(
            model_name='categoryinfo',
            name='unique_GroupInfo',
        ),
        migrations.RenameField(
            model_name='categoryinfo',
            old_name='Group',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Group',
            new_name='Category',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('Order',), name='unique_Category'),
        ),
        migrations.AddConstraint(
            model_name='categoryinfo',
            constraint=models.UniqueConstraint(fields=('Category', 'Language'), name='unique_CategoryInfo'),
        ),
    ]
