# Generated by Django 3.1.7 on 2021-04-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210403_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'verbose_name_plural': 'Categories Info'},
        ),
        migrations.AddField(
            model_name='category',
            name='Slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
