# Generated by Django 3.1.7 on 2021-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210404_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
