# Generated by Django 3.1.7 on 2021-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SetProducts',
            field=models.ManyToManyField(blank=True, related_name='_product_SetProducts_+', to='products.Product'),
        ),
    ]
