# Generated by Django 3.2 on 2021-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_setproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='DateAdded',
            field=models.DateField(blank=True, help_text='Date when this product became available to public', null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='DateRemoved',
            field=models.DateField(blank=True, help_text='Date when this product became unavailable to order', null=True, verbose_name='Date Removed'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Name',
            field=models.CharField(help_text='Full product name with Series before name. No Category should be included.', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Specification',
            field=models.CharField(blank=True, help_text='Specification for product: size, weight etc.', max_length=255, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='Text',
            field=models.TextField(blank=True),
        ),
    ]
