# Generated by Django 3.1.7 on 2021-04-14 07:17

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210413_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(help_text='Category to which this product belongs', on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='Text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
