# Generated by Django 3.2 on 2021-04-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productinfo_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryinfo',
            old_name='Tagline',
            new_name='ShortDesc',
        ),
    ]
