# Generated by Django 3.2 on 2021-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Product',
            field=models.ManyToManyField(blank=True, related_name='tags_of_product', to='products.Product'),
        ),
    ]
