# Generated by Django 3.2 on 2021-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='PV',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
