# Generated by Django 3.2.2 on 2021-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_price_gft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
