# Generated by Django 3.2.9 on 2021-11-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStart', models.DateTimeField()),
                ('DateEnd', models.DateTimeField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PV', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Comment', models.CharField(blank=True, max_length=255)),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('Product', 'Currency', 'DateStart', 'DateEnd'), name='unique_Discount'),
        ),
    ]
