# Generated by Django 3.2.9 on 2021-12-08 10:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20211125_0917'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('DateEnd__gte', django.db.models.expressions.F('DateStart'))), name='check_Discount_Dates_are_in_correct_order'),
        ),
    ]
