# Generated by Django 3.2.9 on 2021-12-09 12:41

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_discount_check_discount_dates_are_in_correct_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateField(help_text='Date when this action is published', verbose_name='Date Added')),
                ('DateStart', models.DateTimeField()),
                ('DateEnd', models.DateTimeField()),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='ActionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=100)),
                ('SubHeader', models.CharField(blank=True, max_length=100)),
                ('Text', markdownx.models.MarkdownxField(blank=True)),
                ('TimestampCreated', models.DateTimeField(auto_now_add=True)),
                ('TimestampModified', models.DateTimeField(auto_now=True)),
                ('Action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.action')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.language')),
            ],
            options={
                'verbose_name_plural': 'Actions Info',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='Action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.action'),
        ),
        migrations.AddConstraint(
            model_name='actioninfo',
            constraint=models.UniqueConstraint(fields=('Action', 'Language'), name='unique_ActionInfo'),
        ),
    ]
