# Generated by Django 3.2.9 on 2021-12-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_action_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SetProducts',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
