# Generated by Django 3.2.9 on 2021-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_product_setproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='Icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
