# Generated by Django 3.2.9 on 2021-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_tab_icon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='unique_Discount',
        ),
        migrations.RemoveConstraint(
            model_name='discount',
            name='check_Discount_Dates_are_in_correct_order',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='DateEnd',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='DateStart',
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('Product', 'Action', 'Currency'), name='unique_Discount'),
        ),
    ]
