# Generated by Django 3.2.9 on 2021-12-17 08:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_tab_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
