# Generated by Django 3.2.9 on 2021-12-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20211217_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='OriginalURL',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
