# Generated by Django 3.2.9 on 2021-12-20 09:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_action_originalurl'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('DateEnd__gte', django.db.models.expressions.F('DateStart')), ('DateEnd__isnull', True), _connector='OR'), name='check_Action_DateEnd_is_greater_or_null'),
        ),
    ]
