# Generated by Django 3.2.9 on 2022-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_action_check_action_dateend_is_greater_or_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='DateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
