# Generated by Django 4.1.1 on 2022-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_discount_pricetype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='unique_Discount',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='unique_Price',
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('Product', 'Action', 'PriceType', 'Currency'), name='unique_Discount'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('Product', 'Currency', 'PriceType', 'DateAdded'), name='unique_Price'),
        ),
    ]
