# Generated by Django 4.1.1 on 2022-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_remove_discount_unique_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='PriceType',
            field=models.CharField(choices=[('C', 'Customer'), ('P', 'Supplier')], max_length=1),
        ),
        migrations.AlterField(
            model_name='price',
            name='PriceType',
            field=models.CharField(choices=[('C', 'Customer'), ('P', 'Supplier')], max_length=1),
        ),
    ]
