# Generated by Django 4.1.1 on 2022-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_discount_pricetype_alter_price_pricetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='PriceType',
            field=models.CharField(choices=[('C', 'Customer'), ('P', 'Partner')], max_length=1),
        ),
        migrations.AlterField(
            model_name='price',
            name='PriceType',
            field=models.CharField(choices=[('C', 'Customer'), ('P', 'Partner')], max_length=1),
        ),
    ]
